<?php
/** localhost:/head.phtml
 *
 * @created   2022-12-25
 * @version   1.0
 * @package   localhost
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<head>
	<!-- icon -->
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

	<!-- Stylesheet -->
	<link type="text/css" href="index.css?<?= date('H') ?>" rel="stylesheet">

	<!-- JavaScript -->
	<script type="text/javascript" src="index.js?<?= date('H') ?>" defer></script>
</head>
