<?php
/** localhost:/switcher.phtml
 *
 * @created   2021-10-20
 * @version   1.0
 * @package   localhost
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
	<div>
		<!-- message area -->
		<div>
			<span id="message" class=""></span>
		</div>

		<!-- version -->
		<form class="block">
			switch php version:
			<select id="switch_php_version">
				<option></option>
				<?php foreach(array(53,54,55,56,70,71,72,73,74,80,81,82,83,84) as $version): ?>
				<option><?php echo $version ?></option>
				<?php endforeach; ?>
			</select>
		</form>
	</div>
